### ISSUE TITLE
Currently Doesn't Install

### ISSUE THREAD

**Issue by sonofwatt84** [rmcaixeta/LocalAnisotropies.jl#103]
I'm currently having trouble installing this because dependencies on older version of GeoStats.jl.  The required older versions of GeoStats.jl doesn't seem to precompile.  

Despite the technical difficulties, I'd love to give this library a try!

**Comment by rmcaixeta** [comment]
Hi Peter
The last few versions of GeoStats had some big refactoring. To use with the new version, LocalAnisotropies needs some adjusts indeed to work. I'll take a look tomorrow to see how big are the changes and update it. Meanwhile, it should work well if you use an older GeoStats version

**Comment by sonofwatt84** [comment]
Thanks Rafael,
I was actually having trouble getting the older GeoStats version to
precompile in my current environment.  I might have time to review the
LocalAnisotropies.jl source code this coming week and try to help out if
you'd like.

**Comment by rmcaixeta** [comment]
I took an initial look yesterday. There were quite a few functions renamed. And even packages deleted/renamed, what might block installing previous versions. I guess I just need to review the adapted kriging functions now, I'll let you know if it works or if I'll need some help

**Comment by rmcaixeta** [comment]
Well, still needs some refactoring to make the code cleaner
But now the last release 0.4 should work well with GeoStats version 0.46
The only thing that will not work in the README example is the plot of the arrows/ellipses into the same Makie environment as the GeoStats (need to migrate the plot recipe later); but should still work well alone with Plots.jl (2D) and VTK export (3D) 
If you still have issues let me know that I'll reopen the issue
